.test_browser: &test_browser
    stage: test
    before_script:
        - npm ci --prefer-offline
    timeout: "15m"
    variables:
        npm_config_cache: &npm_cache_path ".npm"
        CHROME_BIN: "chromium-browser"
        MAPBOX_API_KEY: "key-is-not-required"
        PRODUCTION: "false"
    script:
        - npm run test:ci
    coverage: '/All files \|\s*(\d+(\.\d+)?)/'

cache:
    - key:
          files:
              - package-lock.json
      paths:
          - *npm_cache_path

stages:
    - lint
    - test

lint:
    stage: lint
    before_script:
        - npm ci --prefer-offline
    timeout: "5m"
    variables:
        npm_config_cache: *npm_cache_path
    script:
        - npm run lint
    allow_failure: true
    image: node:14

test:chrome_89:
    <<: *test_browser
    image: zenika/alpine-chrome:89-with-node-14
    allow_failure: true

test:chrome_86:
    <<: *test_browser
    image: zenika/alpine-chrome:86-with-node-14
    allow_failure: true
